### ISSUE TITLE
use the error argument of callbacks in pemFioi/beaver-task-2.0.js

### ISSUE THREAD

**Issue by eroux** [France-ioi/bebras-modules#1]
According to the API documentation, all functions have two callbacks as last arguments, one for success (the one we're currently using), and another for error. The error callback is not mandatory, and it doesn't really matter if it's not used. The problem is with 

``` js
task.gradeAnswer = function(strAnswer, answerToken, callback, gradedLevel)
```

where the `gradedLevel` argument is used instead of the `error` argument. That breaks the `platform-pr.js` file that needs a [not to call the error argument](https://github.com/France-ioi/bebras-modules/blob/master/integrationAPI.01/official/platform-pr.js#L130) because of this, making a difference with the [vanilla file](https://github.com/France-ioi/pem-task/blob/master/platform-pr.js#L130).

**Comment by nir-lavee** [comment]
That function signature comes from [this call](https://github.com/France-ioi/bebras-modules/blob/6a2a6d3a17637c427a8a468dfea70b4df4ecd64b/integrationAPI.01/installationAPI.01/pemFioi/buttonsAndMessages.js#L716-L751) in `buttonsAndMessages.js`.

So the current behavior of `task.gradeAnswer` is: if `gradedLevel` is given, `task.gradeAnswer` provides the score and message for the specified level. Otherwise (if `null`), it provides the best score and message obtained in any level (via `displayHelper.sendBestScore`).

Would adding `gradedLevel` (before `callback`, not after) be a reasonable modification to the current API?

This would mean also adding a `null` argument for `gradedLevel` in all relevant calls to `gradeAnswer`/`gradeTask`, and changing the order of parameters in all 2015 tasks too (because they defined `gradeAnswer` with `gradedLevel` themselves). From a quick look, this doesn't look like a difficult change, at least in `bebras-modules`. @eroux, @mathias-hiron, does that make sense? Are there preferable alternatives?

**Comment by mathias-hiron** [comment]
Hi,

the concept of level should not appear at all in the API. Only an internal
function should include such a parameter, not the one that implements the
API.

**Comment by nir-lavee** [comment]
Okay. I could change said call in `buttonsAndMessages.js` from `gradeAnswer` to some internal name, and make `beaver-task-2.0.js`, and all old tasks, conform to it. In each place I would also add a "real" `gradeAnswer` (which would just use that internal function, easy to add). Would that work?

**Comment by mathias-hiron** [comment]
This sounds reasonable to me, yes. Thanks.

**Comment by eroux** [comment]
thanks!
